### PR TITLE
Refactor names and comments for readability

### PR DESCRIPTION
**Pull request by Ria9993**
Looks like we need to get coding convention.

### CODE REVIEW

**Comment by haelime** [comment]
CI failed. you should fix and re-request

IRCPP/srcs/Server.cpp:152:30

**Comment by haelime** [comment]
LGTM

**Comment by bentraxgel** [comment]
what means `KQUEUE_FD mhKqueue;`?

member h..... Kqueue

**Comment by Ria9993** [comment]
@bentraxgel That means a "Handle". Just another name for "File Descriptor".

**Pull request merged**
